### ISSUE TITLE
programme occasional fails, still in tray but no scroll-locking

### ISSUE THREAD

**Issue by adambonneruk** [adambonneruk/awake#3]
the tray icon is still present but the scrolllocking doesnt occur, it can happen after minutes or hours

**Comment by adambonneruk** [comment]
got this error in powershell, could be the reason:

```
PS C:\Users\redacted\github\awake> python.exe .\awake.pyw
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\redacted\github\awake\awake.pyw", line 22, in second_thread
    press('scrolllock')
  File "C:\Users\redac\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pyautogui\__init__.py", line 597, in wrapper
    failSafeCheck()
  File "C:\Users\redact\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pyautogui\__init__.py", line 1722, in failSafeCheck
    raise FailSafeException(
pyautogui.FailSafeException: PyAutoGUI fail-safe triggered from mouse moving to a corner of the screen. To disable this fail-safe, set pyautogui.FAILSAFE to False. DISABLING FAIL-SAFE IS NOT RECOMMENDED.
```
